baseURL = "/"
languageCode = "en-us"
title = "Defense Travel Management Office"
theme = "uswds-dtmo"

sectionPagesMenu = "main"

########
# Global Navigation
# Position is determined by weight (lower number comes first)
# Convention: xyy
# x  = top level section
# yy = secondary pages
# tertiary pages probably shouldn’t show up in the global nav
########

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "handbook"
    name = "Traveler's Handbook"
    url = "/handbook"
    weight = 100

    [[menu.main]]
      identifier = "new-employees"
      name = "For New Employees"
      url= "/handbook/new-employees"
      parent ="handbook"
      weight = 101

    [[menu.main]]
    	identifier = "travel-tdy"
    	name = "TDY Travel"
    	url = "/handbook/travel-tdy"
    	parent ="handbook"
    	weight = 102

    [[menu.main]]
    	identifier = "travel-international"
    	name = "International Travel"
    	url = "/handbook/travel-international"
    	parent ="handbook"
    	weight = 103

    [[menu.main]]
    	identifier = "moving-living-abroad"
    	name = "Moving, Permanent Change of Station, and Living Abroad"
    	url = "/handbook/moving-living-abroad"
    	parent ="handbook"
    	weight = 104

    [[menu.main]]
      identifier = "travel-administrators"
      name = "Travel Administrators"
      parent = "handbook"
      url = "/support/travel-administrators/"
      weight = 106

  [[menu.main]]
    name = "Travel Administrators Reference"
    parent = "handbook"
    url = "/support/travel-administrators/reference-materials/"
    weight = 107

  [[menu.main]]
    identifier = "support"
    name = "Get Support"
    url = "/support"
    weight = 200

  [[menu.main]]
    identifier = "calculators"
    name = "Calculators"
    url = "/calculators"
    weight = 300

  [[menu.main]]
    identifier = "policy"
    name = "Policy & Regulations"
    url = "/policy"
    weight = 400
