baseURL = "http://example.org/"
languageCode = "en-us"
title = "Defense Travel Management Organization"
theme = "uswds-dtmo"

sectionPagesMenu = "main"

########
# Global Navigation
# Position is determined by weight (lower number comes first)
# Convention: xyy
# x  = top level section
# yy = secondary pages
# tertiary pages probably shouldn’t show up in the global nav
########

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "handbook"
    name = "Traveler's Handbook"
    url = "/handbook"
    weight = 100

 [[menu.main]]
    identifier = "travel-administrators"
    name = "Travel Administrators"
    parent = "Support"
    url = "/support/travel-administrators/"
    weight = 101

  [[menu.main]]
    name = "Travel Administrators Reference"
    parent = "Support"
    url = "/support/travel-administrators/reference-materials/"
    weight = 102

  [[menu.main]]
    identifier = "support"
    name = "Get Support"
    url = "support"
    weight = 200

  [[menu.main]]
    identifier = "calculators"
    name = "Calculators"
    url = "calculators"
    weight = 300

  [[menu.main]]
    identifier = "policy"
    name = "Policy & Regulations"
    url = "policy"
    weight = 400


